<nav class="navbar navbar-expand-md navbar-dark fixed-top" id="banner">
    <div class="container">
        <!-- Brand -->
        <a class="navbar-brand" href="<?= $this->_router->get(['controller' => 'home']) ?>"><span>Warehouse</span> Management System</a>

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->_router->get(['controller' => 'home']) ?>">
                        Home
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Products
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="<?= $this->_router->get(['controller' => 'product']) ?>">
                            List
                        </a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->_router->get(['controller' => 'warehouse']) ?>">
                        Warehouse Calculator
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div id="header-height-fix"></div>