<h1>Product Details</h1>



<?php if (!empty($this->product)) { ?>

    <table class="table">

        <tbody>
            <tr>
                <th>Name</th>
                <td><?= $this->product['description']['name'] ?></td>
            </tr>
            <tr>
                <th>ID</th>
                <td><?= $this->product['product_id'] ?></td>
            </tr>
            <tr>
                <th>Model</th>
                <td><?= $this->product['model'] ?></td>
            </tr>
            <tr>
                <th>Weight</th>
                <td><?= number_format($this->product['weight'], 2, '.', '') ?></td>
            </tr>
            <tr>
                <th>Dimensions</th>
                <td>
                    W: <?= number_format($this->product['width'], 2, '.', '') ?> mm
                    L: <?= number_format($this->product['length'], 2, '.', '') ?> mm
                    H: <?= number_format($this->product['height'], 2, '.', '') ?> mm
                </td>
            </tr>
            <tr>
                <th>Date added</th>
                <td><?= date('Y-m-d', strtotime($this->product['date_added']))  ?></td>
            </tr>
            <tr>
                <th>Status</th>
                <td><?= $this->product['status'] ? 'active' : 'inactive' ?></td>
            </tr>
            <tr>
                <th>Description</th>
                <td><?= $this->product['description']['description'] ?></td>
            </tr>
        </tbody>
    </table>

<?php } else { ?>
    <h4><i>Entity not found</i></h4>
<?php } ?>

<div class="row">
    <div class="col-md-2">
        <a href="<?= $this->_router->get([
                        'controller' => $this->_controllerName
                    ]) ?>" class="btn btn-info btn-block">Back</a>
    </div>
</div>