<h1>Warehouse Dimensions Calculator</h1>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <form method="POST">
      <div class="form-group">
        <label for="warehouseHeight">Warehouse Height: <span class="slider-value"><?= $this->postHeight ?? 3.6 ?></span> m</label>
        <input min="2" value="<?= $this->postHeight ?? 3.6 ?>" step="0.1" max="15" type="range" class="form-control-range" id="warehouseHeight" name="warehouseHeight">
      </div>

      <div class="form-group">
        <input data-toggle-target="js-warehouse-length" <?= !empty($this->setWarehouseLength) ? 'checked' : '' ?> type="checkbox" class="form-check-input js-toggle-input" id="setLength" name="setLength">
        <label class="form-check-label" for="setLength">Set Warehouse Length</label>
      </div>

      <div class="form-group js-warehouse-length initially-hidden">
        <label for="warehouseLength">Warehouse Length: <span class="slider-value"><?= $this->postLength ?? 3.6 ?></span> m</label>
        <input min="1" value="<?= $this->postLength ?? 3.6 ?>" step="0.1" max="500" type="range" class="form-control-range" id="warehouseLength" name="warehouseLength">
      </div>

      <div class="form-group">
        <label for="desiredProductQty">Desired Product Quantity: <span class="slider-value"><?= $this->postProductQty ?? 5 ?></span></label>
        <input min="1" step="1" max="20" value="<?= $this->postProductQty ?? 5 ?>" type="range" class="form-control-range" id="desiredProductQty" name="desiredProductQty">
      </div>

      <div class="form-group">
        <input type="submit" name="submit" class="form-control btn btn-success" value="Calculate">
      </div>
    </form>
  </div>
</div>


<?php
if (
  !empty($this->warehouseWidth) &&
  !empty($this->warehouseLength) &&
  !empty($this->warehouseHeight)
) { ?>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <p>Warehouse Dimensions:
        W: <?= number_format($this->warehouseWidth, 2, '.', '')  ?> m,
        L: <?= number_format($this->warehouseLength, 2, '.', '') ?> m,
        H: <?= number_format($this->warehouseHeight, 2, '.', '') ?> m,
        V: <?= number_format($this->warehouseVolume, 2, '.', '') ?> m³
      </p>
      <p>Packed: 
      <?= $this->packedProducts ?> products 
      (in <?= $this->packedBoxes ?> boxes) / 
      Not Packed: <?= $this->unpacked ?> products</p>
    </div>
  </div>
  <div id="container">
    <div id="cube">
      <div id='face-a' class='face'>Width: <?= number_format($this->warehouseWidth, 2, '.', '')  ?> m</div>
      <div id='face-b' class='face'>Length: <?= number_format($this->warehouseLength, 2, '.', '')  ?> m</div>
      <div id='face-c' class='face'>Width: <?= number_format($this->warehouseWidth, 2, '.', '')  ?> m</div>
      <div id='face-d' class='face'>Height: <?= number_format($this->warehouseHeight, 2, '.', '')  ?> m</div>
      <div id='face-e' class='face'>Length: <?= number_format($this->warehouseLength, 2, '.', '')  ?> m</div>
    </div>
  </div>
<?php }

?>